export { usePurchasesTrend } from '@/features/dashboard/hooks/use-purchases-trend'
export { usePurchasesYears } from '@/features/dashboard/hooks/use-purchases-years'
export { useMonthHighestPurchasesAmount } from '@/features/dashboard/hooks/use-month-highest-purchases-amount'
export { useMonthLowestPurchasesAmount } from '@/features/dashboard/hooks/use-month-lowest-purchases-amount'
export { useMonthTotalPurchasesAmount } from '@/features/dashboard/hooks/use-month-total-purchases-amount'
export { useTotalPurchasesAmount } from '@/features/dashboard/hooks/use-total-purchases-amount'
