import { date, index, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'
import { uuidv7 } from 'uuidv7'
import { cards } from '@/db/schema/cards'
import { invoices } from '@/db/schema/invoices'
import { subscriptions } from '@/db/schema/subscriptions'

export const purchases = pgTable(
  'purchases',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => uuidv7()),

    cardId: text('card_id')
      .notNull()
      .references(() => cards.id, { onDelete: 'cascade' }),

    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),

    // Non-null when auto-generated by a subscription
    subscriptionId: text('subscription_id').references(() => subscriptions.id, {
      onDelete: 'set null',
    }),

    description: text('description').notNull(),
    category: text('category'),
    purchaseDate: date('purchase_date').notNull(),
    installmentsCount: integer('installments_count').notNull(),

    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  table => [
    index('purchases_card_id_idx').on(table.cardId),
    index('purchases_invoice_id_idx').on(table.invoiceId),
    index('purchases_subscription_id_idx').on(table.subscriptionId),
  ],
)
